install.packages("netmeta")
install.packages("rgl")
if (!require("devtools")) {
    install.packages("devtools")
}
devtools::install_github("MathiasHarrer/dmetar")

# Code for functional scoring analysis network:

library(netmeta)
data1 <- read.csv("C:\\Users\\Administrator\\Desktop\\nma_analysis\\r_c.csv")
p1 <- pairwise(trt, mean = mean, sd = sd, n = n, studlab = study, data = data1, sm = "MD", fixed = FALSE, random = TRUE)
net1 <- netmeta(p1)
summary(net1)
pdf("network cs.pdf")
netgraph(net1, points = TRUE, cex.points = 2, cex = 1, thickness = "se.fixed", seq = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"), multiarm = TRUE, col.multiarm = "purple", number.of.studies = TRUE, labels = paste0(trts, " (n=", n.trts,")"))
dev.off()
pdf("forest cs.pdf", width = 8, height = 5)
forest(net1, ref = "1", xlim = c(-30, 30), xlab = "Functional Scoring", leftcols = c("studlab", "k"), leftlabs = c("Contrast\nto Placebo", "Direction\nComparions"), sortvar = -te, drop = TRUE, smlab = "Random Effects Model")
dev.off()
netleague(net1, digits = 2)
league <- netleague(net1, digits = 2, bracket = "(", separator = ",", seq = netrank(net1))
write.table(league$random, file = "league-cs.csv", row.names = FALSE, col.names = FALSE, sep = ",")
ran1 <- rankogram(net1, nsim = 10000)
pdf("rankogram-cs.pdf", width = 10, height = 5)
plot(ran1, type = "l")
dev.off()
pdf("node-splitting forest-cs.pdf", height = 3)
ns1 <- netsplit(net1)
print(netsplit(net1), digits = 2)
forest(ns1, fontsize = 6, spacing = 0.5, addrow.subgroups = FALSE)
dev.off()
pdf("funnel plot-cs.pdf")
ord <- c("5", "13", "10", "9", "1", "2", "12", "11", "3", "6", "4", "8", "7")
funnel(net1, order = ord, linreg = TRUE)
dev.off()
library(dmetar)
pdf("contribution cs.pdf")
p11 <- direct.evidence.plot(net1)
plot(p11)
dev.off() 

# Code for pain scoring analysis network:

library(netmeta)
data2 <- read.csv("C:\\Users\\Administrator\\Desktop\\nma_analysis\\r_v.csv")
p2 <- pairwise(trt, mean = mean, sd = sd, n = n, studlab = study, data = data2, sm = "MD")
net2 <- netmeta(p2)
summary(net2)
pdf("network plot vas.pdf")
netgraph(net2, points = TRUE, cex.points = 2, cex = 1, thickness = "se.fixed", seq = c("1", "2", "3", "4", "6", "7", "8"), multiarm = TRUE, col.multiarm = "purple", number.of.studies = TRUE, labels = paste0(trts, " (n=", n.trts,")"))
dev.off()
pdf("forest plot vas.pdf", width = 8, height = 5)
forest(net2, ref = "1", xlim = c (-1, 5), xlab = " Pain Scoring", leftcols = c("studlab", "k"), leftlabs = c("Contrast\nto Placebo", "Direction\nComparions"), sortvar = -te, drop = TRUE, smlab = "Random Effects Model")
dev.off()
netleague(net2, digits = 2)
league <- netleague(net2, digits = 2, bracket = "(", separator = ",", seq = netrank(net2))
write.table(league$random, file = "league-vas.csv", row.names = FALSE, col.names = FALSE, sep = ",")
pdf("rankogram-vas.pdf")
ran1 <- rankogram(net2, nsim = 10000)
plot(ran1, type = "l")
dev.off()
pdf("node-splitting forest-vas.pdf", height = 5)
ns1 <- netsplit(net2)
print(netsplit(net2), digits = 2)
forest(ns1, fontsize = 6, spacing = 0.5, addrow.subgroups = FALSE)
dev.off()
pdf("funnel plot-vas.pdf")
ord <- c("1", "7", "2", "4", "3", "8", "6")
funnel(net2, order = ord, linreg = TRUE)
dev.off()
library(dmetar)
pdf("contribution vas.pdf")
p22 <- direct.evidence.plot(net2)
plot(p22)
dev.off()
